### ISSUE TITLE
"in reply to" not stripped for German mails

### ISSUE THREAD

**Issue by fefrei** [discourse/email_reply_trimmer#4]
I've caught another "in reply to"-line in my German Discourse install:

```
Am 21.04.2016 17:48 schrieb "Max Mustermann"
```

Here's a (redacted) fragment of the raw email:

```
Bin gleichzeitig robust, sofern n=C3=B6tig.

Am 21.04.2016 17:48 schrieb "Max Mustermann" <noreply@discourse.pseuco.co=
m
>:

> max.mustermann <https://discourse.pseuco.com/users/max.mustermann> Ma=
x
> Mustermann <https://discourse.pseuco.com/users/max.mustermann>
> 21. April
>
> Vielleicht noch eine wichtige Frage:
```

**Comment by ZogStriP** [comment]
Seems like there's an issue with the encoding. Can you send me the raw email via PM on https://meta.discourse.org?

**Comment by fefrei** [comment]
I sent you [a PM](https://meta.discourse.org/t/in-reply-to-not-stripped-for-german-mails-4/42999).

**Comment by ZogStriP** [comment]
Tracked on meta.
