### ISSUE TITLE
Add support for (configurable?) hot-word signature delimiters

### ISSUE THREAD

**Issue by lloeki** [discourse/email_reply_trimmer#7]
Some signatures aren't delimited by symbols but by specific words or phrases standing alone on a line, such as "Regards", "Cheers", "All the best", "Cordialement", "Bien à vous"...

See [this issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/2700#note_19947419) for some relevant details.

**Comment by ZogStriP** [comment]
Feel free to submit a PR ;)
